import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/provider";
import { store } from "./redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie Listing app",
  description: "Generated by Xieno team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers store={store}>
         {children}
       </Providers>
        </body>
    </html>
  );
}
